return {
	-- ОСНОВНАЯ МУЗЫКА
	["MAIN/music"] = {
		Id = 78560130014615, 
		Loop = true,
	},

	-- МУЗЫКА ИВЕНТОВ
	["BONE_RAIN/music"] = {
		Id = 109559329984337,
		Loop = true,
	},

	["GOLDEN_HOUR/music"] = {
		Id = 138627726943804,
		Loop = true,
	},

	["DOG_RUSH/music"] = {
		Id = 120874159683228,
		Loop = true,
	},

	["TREASURE_FEVER/music"] = {
		Id = 127345232419357,
		Loop = true,
	},

	["CRYSTAL_STORM/music"] = {
		Id = 73548210979575,
		Loop = true,
	},

	["EARTHQUAKE/music"] = {
		Id = 83760096401168,
		Loop = true,
	},

	["TIME_WARP/music"] = {
		Id = 111826501420223,
		Loop = true,
	},

	["CURSED_FOG/music"] = {
		Id = 101225909395482,
		Loop = true,
	},

	["BLACKOUT/music"] = {
		Id = 129261783425870,
		Loop = true,
	},

	["UFO_INVASION/music"] = {
		Id = 98206744403149,
		Loop = true,
	},

	["RAINBOW_RIFT/music"] = {
		Id = 76546242991969,
		Loop = true,
	},

	["NULL_HOUR/music"] = {
		Id = 87423711872287,
		Loop = true,
	},

	["THE_VOID_OPENS/music"] = {
		Id = 76361076395656,
		Loop = true,
	},
}